# Generated by Django 5.0.7 on 2024-07-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_user_alter_item_name_alter_item_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='quantity',
            new_name='quantityInStock',
        ),
        migrations.AddField(
            model_name='item',
            name='quantitySold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='revenue',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ManyToManyField(to='inventory.supplier'),
        ),
    ]
