# Generated by Django 5.0.7 on 2024-07-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplier_rename_quantity_item_quantityinstock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='supplier',
            new_name='suppliers',
        ),
    ]
