# Generated by Django 5.0.7 on 2024-07-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='revenue',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
